version: '3.8'

services:
  video-wall-backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static_content:/app/static_content
      - ./uploads:/app/uploads
      - ./config.yaml:/app/config.yaml
      - ./video_wall.db:/app/video_wall.db
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    restart: unless-stopped
    networks:
      - video-wall-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static_content:/usr/share/nginx/html/static
    depends_on:
      - video-wall-backend
    networks:
      - video-wall-network

networks:
  video-wall-network:
    driver: bridge
